[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/consulting"
  to = "/consulting.html"
  status = 200

[[redirects]]
  from = "/coaching"
  to = "/coaching.html"
  status = 200

[[redirects]]
  from = "/apply"
  to = "/consulting"
  status = 301

[[redirects]]
  from = "/apply.html"
  to = "/consulting.html"
  status = 301

[[redirects]]
  from = "/masterclass"
  to = "/coaching"
  status = 301

[[redirects]]
  from = "/masterclass.html"
  to = "/coaching.html"
  status = 301

[[redirects]]
  from = "/superhuman"
  to = "/superhuman.html"
  status = 200

[[redirects]]
  from = "/architecture"
  to = "/architecture.html"
  status = 200

[[redirects]]
  from = "/break-point"
  to = "/break-point/index.html"
  status = 200

[[redirects]]
  from = "/break-point/results"
  to = "/break-point/results/index.html"
  status = 200

[[redirects]]
  from = "/break-point/book"
  to = "/break-point/book/index.html"
  status = 200
